dist: trusty
os: linux
language: minimal
cache:
  ccache: true
  directories:
    - $HOME/.ccache
git:
  quiet: true

branches:
  only:
  - master
  - dev

stages:
  - test

env:
  global:
    - CCACHE_SIZE=200M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CCACHE_DIR=$HOME/.ccache

before_install:
  - sudo apt-get install libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils -y -q
  - sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libboost-iostreams-dev -y -q
  - sudo apt-get install software-properties-common -y -q
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - sudo apt-get install libdb4.8-dev libdb4.8++-dev -y -q
  - sudo apt-get install libminiupnpc-dev -y -q
  - sudo apt-get install libzmq3-dev -y -q

install:
  true
  
before_script:
  - sh ./autogen.sh
  - sh ./configure
  - make -j3
  - chmod -R +x ./test/functional
  - ccache --max-size=$CCACHE_SIZE
  - ln -s $TRAVIS_BUILD_DIR/src/magnachaind $TRAVIS_BUILD_DIR/src/magnachaind-side

# after_script:
# TODO: commit something

notifications:
  email:
    recipients:
      - notify.dev@yandex.com
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: test
      name: contract test
      script: 
        cat /proc/sys/kernel/threads-max && free -h && python3 ./test/functional/test_runner.py --runtag contract

    - stage: test
      name: sidechain test
      script: 
        cat /proc/sys/kernel/threads-max && free -h && python3 ./test/functional/test_runner.py --runtag sidechain

    - stage: test
      name: wallet test
      script: 
        cat /proc/sys/kernel/threads-max && free -h && python3 ./test/functional/test_runner.py --runtag wallet

    - stage: test
      name: mempool test
      script: 
        cat /proc/sys/kernel/threads-max && free -h && python3 ./test/functional/test_runner.py --runtag mempool

    - stage: test
      name: rpc test
      script: 
        cat /proc/sys/kernel/threads-max && free -h && python3 ./test/functional/test_runner.py --runtag rpc

    - stage: test
      name: feature test
      script: 
        cat /proc/sys/kernel/threads-max && free -h && python3 ./test/functional/test_runner.py --runtag feature