.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. magnachain_qt test_magnachain_qt
clean: FORCE
	$(MAKE) -C .. magnachain_qt_clean test_magnachain_qt_clean
check: FORCE
	$(MAKE) -C .. test_magnachain_qt_check
magnachain-qt magnachain-qt.exe: FORCE
	 $(MAKE) -C .. magnachain_qt
