.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. celllink_qt test_celllink_qt
clean: FORCE
	$(MAKE) -C .. celllink_qt_clean test_celllink_qt_clean
check: FORCE
	$(MAKE) -C .. test_celllink_qt_check
celllink-qt celllink-qt.exe: FORCE
	 $(MAKE) -C .. celllink_qt
